version: "3.3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=leo
      - POSTGRES_PASSWORD=Monotiti1
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=leonidas.ramirez.q@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Monotiti1
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Monotiti1
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_PASSWORD=Monotiti1
    ports:
      - 8080:80
